exclude:     ['README.md', 'Gemfile*', 'vendor', 'bin']
markdown: kramdown
permalink: /blog/:year/:month/:day/:title
sass:
  sass_dir: _scss

defaults:
  -
    scope:
      path: "" # match all files in the project
    values:
      layout: page
