# MySQL.  Versions 4.1 and 5.0 are recommended.
#
# Install the MySQL driver:
#   gem install mysql

development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chchspace_development
  pool: 5
  username: root
  password:

test:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chchspace_test
  pool: 5
  username: root
  password:

# TODO: create
production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: chchspace_production
  pool: 5
  username: chchspace_production
  password:
